---
- hosts: all
  sudo: yes
  tasks:
    - name: update apt
      apt: update_cache=yes
    - name: install Git
      apt: package=git state=present
    - name: install PHP 5
      apt: package=php5-cli state=present
    - name: install PHP 5 XSL extension (for PHPDoc)
      apt: package=php5-xsl state=present
    - name: install curl
      apt: package=curl state=present
    - name: upgrade any old packages
      apt: upgrade=dist
    - name: install Composer
      shell: creates=/vagrant/composer.phar curl -sS https://getcomposer.org/installer | php -- --install-dir=/vagrant
    - name: install project dependencies
      shell: chdir=/vagrant ./composer.phar install
    - name: get Boris (better PHP REPL)
      git: repo=git://github.com/d11wtq/boris.git dest=/usr/local/boris
    - name: install Boris
      file: path=/usr/local/bin/boris state=link src=/usr/local/boris/bin/boris mode=0755